Marina and Cleo notes from Tuesday evening whiteboard session
FAC9/notes pull request #36
Opened 2016-12-06 18:42 UTC by marisid

2016-12-06 23:50 UTC, jsms90 requested changes

2016-12-06 23:50 UTC, jsms90 commented on week8-oauth/project-workflow.md
> +
Maybe collate lines 8-15 & 19-25?

2016-12-07 18:28 UTC, marisid commented
I've tried to combine the notes :smile: Also, I think we need the image (although we don't reference it in the readme) just as a resource, it's from the Monday morning walkthrough. What do you think?

2016-12-15 23:56 UTC, jsms90 approved these changes

2016-12-15 23:56 UTC, merged